spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
          - path=/ratings/**
          
          
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
          - path=/users/**
          
          
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
          - path=/hotel/**
  
  application:
    name: APIGATEWAY
          


eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
server:
  port: 8084
  