
server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: '#Sky@@71'
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
  
  application:
    name: HotelService