spring:
  application:
    name: UserService
    
  datasource:
    username: root
    password: '#Sky@@71'
    url: jdbc:mysql://localhost:3306/userservice
    
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
  
  
  config:
    import: optional:configserver:http://localhost:8085
    
  profiles:
    active:
    - dev
    
    
server:
  port: 8081
