spring:
  application:
    name: UserService
    
  datasource:
    username: root
    password: '#Sky@@71'
    url: jdbc:mysql://localhost:3306/userservice
    
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
  
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka
    
server:
  port: 8081
