spring:
  application:
    name: UserService
    
  datasource:
    username: root
    password: '#Sky@@71'
    url: jdbc:mysql://localhost:3306/userservice
    
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    
    
server:
  port: 8081
